site_name: "Subaru Reference"
site_url: https://subaru.locomoco.dev

# Repository
repo_name: GitLab Repo
repo_url: https://gitlab.com/locomoco-dev/subaru-reference
edit_uri: ""

theme:
    name: shadcn
    show_title: true
    show_stargazers: false
    pygments_style:
        light: shadcn-light
        dark: github-dark
    icon: null
    topbar_sections: false
    show_datetime: false

markdown_extensions:
    - admonition
    - codehilite

plugins:
    - glightbox

extra_javascript:
    - js/bilinear-interpolation.js
